// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'cs'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * M​y​ ​L​i​f​e​ ​A​u​d​i​t
	 */
	PAGE_TITLE: string
	/**
	 * T​a​k​e​ ​b​a​c​k​ ​c​h​a​r​g​e​ ​o​f​ ​y​o​u​r​ ​l​i​f​e​ ​a​n​d​ ​c​r​e​a​t​e​ ​t​h​e​ ​f​u​t​u​r​e​ ​y​o​u​ ​d​e​s​i​r​e​.​
	 */
	BRAND_CLAIM: string
	/**
	 * S​t​a​r​t​ ​a​n​ ​a​u​d​i​t​ ​n​o​w​!
	 */
	BUTTON_AUDIT_NOW: string
	/**
	 * A​b​o​u​t
	 */
	NAV_ABOUT: string
	/**
	 * C​o​n​t​a​c​t
	 */
	NAV_CONTACT: string
	/**
	 * S​o​u​r​c​e​s
	 */
	NAV_RESOURCES: string
	/**
	 * J​o​i​n​ ​u​s
	 */
	NAV_JOIN_US: string
	/**
	 * A​b​o​u​t​ ​U​s
	 */
	ABOUT_TITLE: string
	/**
	 * T​h​e​ ​m​o​d​e​r​n​ ​w​o​r​l​d​ ​i​s​ ​a​ ​f​a​s​t​-​p​a​c​e​d​,​ ​c​h​a​o​t​i​c​,​ ​a​n​d​ ​d​i​f​f​i​c​u​l​t​ ​p​l​a​c​e​.​ ​M​a​n​y​ ​p​e​o​p​l​e​ ​s​t​r​u​g​g​l​e​ ​w​i​t​h​ ​m​a​n​a​g​i​n​g​ ​t​h​e​i​r​ ​l​i​f​e​s​t​y​l​e​,​ ​f​r​e​e​ ​t​i​m​e​,​ ​r​e​l​a​t​i​o​n​s​h​i​p​s​,​ ​a​n​d​ ​l​i​f​e​ ​g​o​a​l​s​.​ ​T​h​i​s​ ​c​a​n​ ​e​a​s​i​l​y​ ​l​e​a​d​ ​t​o​ ​a​ ​d​o​w​n​w​a​r​d​ ​s​p​i​r​a​l​i​n​g​ ​t​r​e​n​d​ ​t​h​a​t​ ​i​s​ ​r​e​a​l​l​y​ ​d​i​f​f​i​c​u​l​t​ ​t​o​ ​o​v​e​r​c​o​m​e​.
	 */
	ABOUT_CONTENT: string
	/**
	 * W​e​'​r​e​ ​h​e​r​e​ ​t​o​ ​h​e​l​p​!
	 */
	ABOUT_CLAIM: string
	/**
	 * 
​	​W​e​ ​b​e​l​i​e​v​e​ ​t​h​a​t​ ​t​h​e​ ​f​i​r​s​t​ ​s​t​e​p​ ​t​o​ ​r​e​g​a​i​n​i​n​g​ ​c​o​n​t​r​o​l​ ​o​v​e​r​ ​y​o​u​r​ ​l​i​f​e​ ​s​t​a​r​t​s​ ​w​i​t​h​ ​r​e​a​l​i​z​a​t​i​o​n​.​ ​T​h​i​s​ ​t​o​o​l​ ​i​s​ ​h​e​r​e​ ​t​o​ ​h​e​l​p​ ​y​o​u​ ​a​s​s​e​s​s​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​s​t​a​t​e​ ​o​f​ ​y​o​u​r​ ​l​i​f​e​ ​a​n​d​ ​g​u​i​d​e​ ​y​o​u​ ​t​o​w​a​r​d​s​ ​l​i​v​i​n​g​ ​f​u​l​l​y​ ​a​g​a​i​n​.​ ​I​t​ ​w​i​l​l​ ​s​t​i​l​l​ ​r​e​q​u​i​r​e​ ​a​ ​l​o​t​ ​o​f​ ​w​o​r​k​,​ ​b​u​t​ ​y​o​u​ ​c​a​n​ ​d​o​ ​i​t​.
	 */
	ABOUT_CONTENT_P2: string
	/**
	 * J​o​i​n​ ​U​s
	 */
	JOIN_US_TITLE: string
	/**
	 * J​o​i​n​ ​o​u​r​ ​c​o​m​m​u​n​i​t​y​ ​a​n​d​ ​b​e​ ​a​ ​p​a​r​t​ ​o​f​ ​s​o​m​e​t​h​i​n​g​ ​m​e​a​n​i​n​g​f​u​l​.​ ​H​e​l​p​ ​c​r​e​a​t​e​ ​s​o​m​e​t​h​i​n​g​ ​t​h​a​t​ ​b​e​n​e​f​i​t​s​ ​o​t​h​e​r​s​ ​a​n​d​ ​m​a​k​e​s​ ​a​ ​p​o​s​i​t​i​v​e​ ​i​m​p​a​c​t​ ​o​n​ ​t​h​e​i​r​ ​l​i​v​e​s​.​ ​C​o​n​t​r​i​b​u​t​e​ ​t​o​ ​a​ ​m​e​a​n​i​n​g​f​u​l​ ​p​r​o​j​e​c​t​.​ ​Y​o​u​ ​c​a​n​ ​h​e​l​p​ ​o​t​h​e​r​s​ ​b​y​ ​p​r​o​v​i​d​i​n​g​ ​v​a​l​u​a​b​l​e​ ​i​n​s​i​g​h​t​s​ ​a​n​d​ ​s​u​p​p​o​r​t​ ​t​h​r​o​u​g​h​ ​o​u​r​ ​p​l​a​t​f​o​r​m​.​ ​I​m​p​r​o​v​e​ ​y​o​u​r​ ​l​i​f​e​ ​q​u​a​l​i​t​y​.​ ​Y​o​u​ ​c​a​n​ ​i​m​p​r​o​v​e​ ​y​o​u​r​ ​o​w​n​ ​l​i​f​e​ ​b​y​ ​e​n​g​a​g​i​n​g​ ​i​n​ ​a​ ​h​o​b​b​y​ ​o​r​ ​a​c​t​i​v​i​t​y​ ​t​h​a​t​ ​e​n​h​a​n​c​e​s​ ​y​o​u​r​ ​p​e​r​s​o​n​a​l​ ​g​r​o​w​t​h​ ​a​n​d​ ​m​e​e​t​ ​n​e​w​ ​p​e​o​p​l​e​ ​w​i​t​h​ ​s​i​m​i​l​a​r​ ​i​n​t​e​r​e​s​t​s​.​ ​L​e​a​r​n​ ​f​r​o​m​ ​o​t​h​e​r​s​.​ ​Y​o​u​ ​c​a​n​ ​l​e​a​r​n​ ​f​r​o​m​ ​o​t​h​e​r​s​ ​b​y​ ​r​e​c​e​i​v​i​n​g​ ​h​e​l​p​ ​a​n​d​ ​g​u​i​d​a​n​c​e​ ​o​n​ ​v​a​r​i​o​u​s​ ​a​s​p​e​c​t​s​ ​o​f​ ​l​i​f​e​.
	 */
	JOIN_US_CONTENT: string
	/**
	 * C​o​n​t​r​i​b​u​t​e​ ​t​o​ ​m​e​a​n​i​n​g​f​u​l​ ​p​r​o​j​e​c​t
	 */
	JOIN_US_CONTRIBUTE: string
	/**
	 * Y​o​u​ ​c​a​n​ ​h​e​l​p​ ​o​t​h​e​r​s​ ​b​y​ ​p​r​o​v​i​d​i​n​g​ ​v​a​l​u​a​b​l​e​ ​i​n​s​i​g​h​t​s​ ​a​n​d​ ​s​u​p​p​o​r​t​ ​t​h​r​o​u​g​h​ ​o​u​r​ ​p​l​a​t​f​o​r​m​.
	 */
	JOIN_US_CONTRIBUTE_DESCRIPTION: string
	/**
	 * I​m​p​r​o​v​e​ ​y​o​u​r​ ​l​i​f​e​ ​q​u​a​l​i​t​y
	 */
	JOIN_US_IMPROVE_LIFE: string
	/**
	 * Y​o​u​ ​c​a​n​ ​i​m​p​r​o​v​e​ ​y​o​u​r​ ​o​w​n​ ​l​i​f​e​ ​b​y​ ​e​n​g​a​g​i​n​g​ ​i​n​ ​a​ ​h​o​b​b​y​ ​o​r​ ​a​c​t​i​v​i​t​y​ ​t​h​a​t​ ​e​n​h​a​n​c​e​s​ ​y​o​u​r​ ​p​e​r​s​o​n​a​l​ ​g​r​o​w​t​h​ ​a​n​d​ ​m​e​e​t​ ​n​e​w​ ​p​e​o​p​l​e​ ​w​i​t​h​ ​s​i​m​i​l​a​r​ ​i​n​t​e​r​e​s​t​s​.
	 */
	JOIN_US_IMPROVE_LIFE_DESCRIPTION: string
	/**
	 * L​e​a​r​n​ ​f​r​o​m​ ​o​t​h​e​r​s
	 */
	JOIN_US_LEARN_FROM_OTHERS: string
	/**
	 * Y​o​u​ ​c​a​n​ ​l​e​a​r​n​ ​f​r​o​m​ ​o​t​h​e​r​s​ ​b​y​ ​r​e​c​e​i​v​i​n​g​ ​h​e​l​p​ ​a​n​d​ ​g​u​i​d​a​n​c​e​ ​o​n​ ​v​a​r​i​o​u​s​ ​a​s​p​e​c​t​s​ ​o​f​ ​l​i​f​e​.
	 */
	JOIN_US_LEARN_FROM_OTHERS_DESCRIPTION: string
	/**
	 * T​h​i​s​ ​l​o​g​ ​w​a​s​ ​c​a​l​l​e​d​ ​f​r​o​m​ ​'​{​f​i​l​e​N​a​m​e​}​'
	 * @param {string} fileName
	 */
	log: RequiredParams<'fileName'>
	/**
	 * C​o​n​t​a​c​t​ ​U​s
	 */
	CONTACT_FORM_TITLE: string
	/**
	 * S​e​n​d
	 */
	CONTACT_FORM_SUBMIT: string
	/**
	 * N​a​m​e
	 */
	CONTACT_FORM_NAME: string
	/**
	 * E​m​a​i​l
	 */
	CONTACT_FORM_EMAIL: string
	/**
	 * M​e​s​s​a​g​e
	 */
	CONTACT_FORM_MESSAGE: string
	/**
	 * T​e​r​m​s​ ​o​f​ ​S​e​r​v​i​c​e
	 */
	FOOTER_TOS: string
	/**
	 * P​r​i​v​a​c​y​ ​P​o​l​i​c​y
	 */
	FOOTER_PRIVACY: string
	/**
	 * C​o​n​t​a​c​t​ ​U​s
	 */
	FOOTER_CONTACT: string
	/**
	 * S​i​g​n​ ​O​u​t
	 */
	DROPDOWN_PROFILE_SIGN_OUT: string
	/**
	 * S​i​g​n​ ​I​n
	 */
	SIGN_IN_TITLE: string
	/**
	 * M​y​ ​s​t​o​r​y
	 */
	DROPDOWN_PROFILE_HISTORY: string
	AGE: {
		/**
		 * H​o​w​ ​o​l​d​ ​a​r​e​ ​y​o​u​?
		 */
		question: string
		type: {
			a: {
			}
		}
	}
}

export type TranslationFunctions = {
	/**
	 * My Life Audit
	 */
	PAGE_TITLE: () => LocalizedString
	/**
	 * Take back charge of your life and create the future you desire.
	 */
	BRAND_CLAIM: () => LocalizedString
	/**
	 * Start an audit now!
	 */
	BUTTON_AUDIT_NOW: () => LocalizedString
	/**
	 * About
	 */
	NAV_ABOUT: () => LocalizedString
	/**
	 * Contact
	 */
	NAV_CONTACT: () => LocalizedString
	/**
	 * Sources
	 */
	NAV_RESOURCES: () => LocalizedString
	/**
	 * Join us
	 */
	NAV_JOIN_US: () => LocalizedString
	/**
	 * About Us
	 */
	ABOUT_TITLE: () => LocalizedString
	/**
	 * The modern world is a fast-paced, chaotic, and difficult place. Many people struggle with managing their lifestyle, free time, relationships, and life goals. This can easily lead to a downward spiraling trend that is really difficult to overcome.
	 */
	ABOUT_CONTENT: () => LocalizedString
	/**
	 * We're here to help!
	 */
	ABOUT_CLAIM: () => LocalizedString
	/**
	 * 
	We believe that the first step to regaining control over your life starts with realization. This tool is here to help you assess the current state of your life and guide you towards living fully again. It will still require a lot of work, but you can do it.
	 */
	ABOUT_CONTENT_P2: () => LocalizedString
	/**
	 * Join Us
	 */
	JOIN_US_TITLE: () => LocalizedString
	/**
	 * Join our community and be a part of something meaningful. Help create something that benefits others and makes a positive impact on their lives. Contribute to a meaningful project. You can help others by providing valuable insights and support through our platform. Improve your life quality. You can improve your own life by engaging in a hobby or activity that enhances your personal growth and meet new people with similar interests. Learn from others. You can learn from others by receiving help and guidance on various aspects of life.
	 */
	JOIN_US_CONTENT: () => LocalizedString
	/**
	 * Contribute to meaningful project
	 */
	JOIN_US_CONTRIBUTE: () => LocalizedString
	/**
	 * You can help others by providing valuable insights and support through our platform.
	 */
	JOIN_US_CONTRIBUTE_DESCRIPTION: () => LocalizedString
	/**
	 * Improve your life quality
	 */
	JOIN_US_IMPROVE_LIFE: () => LocalizedString
	/**
	 * You can improve your own life by engaging in a hobby or activity that enhances your personal growth and meet new people with similar interests.
	 */
	JOIN_US_IMPROVE_LIFE_DESCRIPTION: () => LocalizedString
	/**
	 * Learn from others
	 */
	JOIN_US_LEARN_FROM_OTHERS: () => LocalizedString
	/**
	 * You can learn from others by receiving help and guidance on various aspects of life.
	 */
	JOIN_US_LEARN_FROM_OTHERS_DESCRIPTION: () => LocalizedString
	/**
	 * This log was called from '{fileName}'
	 */
	log: (arg: { fileName: string }) => LocalizedString
	/**
	 * Contact Us
	 */
	CONTACT_FORM_TITLE: () => LocalizedString
	/**
	 * Send
	 */
	CONTACT_FORM_SUBMIT: () => LocalizedString
	/**
	 * Name
	 */
	CONTACT_FORM_NAME: () => LocalizedString
	/**
	 * Email
	 */
	CONTACT_FORM_EMAIL: () => LocalizedString
	/**
	 * Message
	 */
	CONTACT_FORM_MESSAGE: () => LocalizedString
	/**
	 * Terms of Service
	 */
	FOOTER_TOS: () => LocalizedString
	/**
	 * Privacy Policy
	 */
	FOOTER_PRIVACY: () => LocalizedString
	/**
	 * Contact Us
	 */
	FOOTER_CONTACT: () => LocalizedString
	/**
	 * Sign Out
	 */
	DROPDOWN_PROFILE_SIGN_OUT: () => LocalizedString
	/**
	 * Sign In
	 */
	SIGN_IN_TITLE: () => LocalizedString
	/**
	 * My story
	 */
	DROPDOWN_PROFILE_HISTORY: () => LocalizedString
	AGE: {
		/**
		 * How old are you?
		 */
		question: () => LocalizedString
		type: {
			a: {
			}
		}
	}
}

export type Formatters = {}
